#!/bin/zsh

# Empty the Trash on all mounted volumes and the main HDD
# Clear Apple’s System Logs to improve shell startup speed
# Clear the useless sleepimage
# Clear download history from quarantine. https://mths.be/bum
alias emptytrash=" \
    sudo rm -rfv /Volumes/*/.Trashes; \
    rm -rfv ~/.Trash/*; \
    sudo rm -rfv /private/var/log/asl/*.asl; \
    sudo rm -v /private/var/vm/sleepimage; \
    sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'; \
"

# Lock the screen (when going AFK)
# alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
# alias afk="osascript -e 'tell application \"System Events\" to sleep'"
# alias afk="open /System/Library/CoreServices/ScreenSaverEngine.app"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# who is using the laptop's iSight camera?
camerausedby() {
	echo "Checking to see who is using the iSight camera… 📷"
	usedby=$(lsof | grep -w "AppleCamera\|USBVDC\|iSight" | awk '{printf $2"\n"}' | xargs ps)
	echo -e "Recent camera uses:\n$usedby"
}

alias brew_update="brew -v update; brew upgrade --force-bottle --cleanup; brew cleanup; brew cask cleanup; brew prune; brew doctor"

# Exclude macOS specific files in ZIP archives
alias zip="zip -x *.DS_Store -x *__MACOSX* -x *.AppleDouble*"

# Quick-Look preview files from the command line
alias ql="qlmanage -p &>/dev/null"

alias logs='journalctl -fu'
alias logs-all='journalctl -u'

# Change working directory to the top-most Finder window location
alias cdf='function __cdf() { cd `osascript -e "tell app \"Finder\" to POSIX path of (insertion location as alias)"`; unset -f cdf; }; cdf'
