#!/bin/zsh

# use `greadlink` to maintain consistancy between macOS and Linux
alias readlink='greadlink'

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"
