#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"
	CMD="$(dirname $(readlink -f $0))/$(basename $0) $@"
	exec sudo $CMD
	exit #?
fi

dotfiles_folder=$HOME/Projects/dotfiles

cp $dotfiles_folder/dnsmasq/dnsmasq.conf /etc/
cp $dotfiles_folder/dnsmasq/resolv.personal /etc/
cp $dotfiles_folder/dnsmasq/resolv.conf /etc/
cp $dotfiles_folder/dnsmasq/hosts.adblock /etc/

cp $dotfiles_folder/dnsmasq/NetworkManager.conf /etc/NetworkManager/

service network-manager restart

service dnsmasq restart