#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"
	CMD="$(dirname $(readlink -f $0))/$(basename $0) $@"
	exec sudo $CMD
	exit #?
fi

cp ./dnsmasq.conf /etc/
cp ./resolv.personal /etc/
cp ./resolv.conf /etc/
cp ./hosts.adblock /etc/

cp ./NetworkManager.conf /etc/NetworkManager/

service network-manager restart

service dnsmasq restart