#!/bin/bash

export DOTFILES=~/Projects/dotfiles
export DOTFILES_DEVICE="macbook_pro"

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

echo "Creating directories"
mkdir -p $HOME/Pictures/Wallpapers $HOME/Pictures/Screenshots $HOME/.config/kitty $HOME/.config/karabiner

echo "Linking yabai config"
ln -sf $device_folder/.yabairc $HOME/.yabairc

echo "Linking skhd config"
ln -sf $device_folder/.skhdrc $HOME/.skhdrc

echo "Linking zsh config"
ln -sf $device_folder/.zshrc $HOME/.zshrc

echo "Linking kitty config"
ln -sf $device_folder/kitty.conf $HOME/.config/kitty/kitty.conf

echo "Linking karabiner config"
ln -sf $device_folder/karabiner.json $HOME/.config/karabiner/karabiner.json

if [ ! -f /usr/local/bin/brew ]; then
	echo "Installing brew"

	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -f $HOME/.nvm ]; then
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
fi

echo "Installing global npm packages"
npm i -g pm2 fatlard1993/zelda

echo "Installing brew apps"
brew tap homebrew/cask-fonts
brew tap mongodb/brew
brew update
brew upgrade
brew install thefuck arp-scan xclip jq font-source-code-pro font-source-sans-pro mongodb-community@3.6
brew services restart yabai

echo "Configuring priv-config"
$DOTFILES/../priv-config/update