#!/bin/bash

export DOTFILES=~/Projects/dotfiles
export DOTFILES_DEVICE="macbook_pro"

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

echo "Creating directories"
mkdir -p $HOME/Pictures/Wallpapers $HOME/Pictures/Screenshots $HOME/.config/kitty $HOME/.config/karabiner $HOME/Library/KeyBindings

echo "Installing/Updating brew apps"
brew tap homebrew/cask-fonts
brew tap homebrew/cask-drivers
brew tap mongodb/brew
brew update
brew upgrade
brew install thefuck arp-scan xclip jq fontconfig font-source-code-pro font-source-sans-pro font-fontawesome font-hack-nerd-font mongodb-community swiftbar visual-studio-code google-chrome karabiner-elements kitty muzzle logitech-options logitech-unifying koekeishiya/formulae/skhd koekeishiya/formulae/yabai redis rabbitmq bettertouchtool postman robo-3t figma docker
brew install --cask docker
sudo yabai --install-sa
brew services restart skhd
brew services restart yabai

echo "Linking yabai config"
ln -sf $device_folder/.yabairc $HOME/.yabairc

echo "Linking skhd config"
ln -sf $device_folder/.skhdrc $HOME/.skhdrc

echo "Linking zsh config"
ln -sf $device_folder/.zshenv $HOME/.zshenv
ln -sf $device_folder/.zshrc $HOME/.zshrc

echo "Linking kitty config"
ln -sf $device_folder/kitty.conf $HOME/.config/kitty/kitty.conf

echo "Linking karabiner config"
ln -sf $device_folder/karabiner.json $HOME/.config/karabiner/karabiner.json

echo "Linking vscode argv config"
ln -sf $device_folder/vscode/argv.json $HOME/.vscode/argv.json

if [ ! -e $HOME/Library/KeyBindings/DefaultKeyBindings.dict ]; then
	echo "Linking DefaultKeyBindings"
	sudo ln -sf $device_folder/DefaultKeyBindings.dict $HOME/Library/KeyBindings/DefaultKeyBindings.dict
fi

if [ ! -f /usr/local/bin/brew ]; then
	echo "Installing brew"

	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -e $HOME/.nvm ]; then
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
fi

echo "Installing global npm packages"
npm i -g pm2 fatlard1993/zelda

echo "Configuring priv-config"
$DOTFILES/../priv-config/update