#!/bin/zsh
## $HOME/.zshrc

zshrcPath="$HOME/.dotfiles/macos/zshenv"

for file in $zshrcPath/*(.); do
	[[ "$file" != "$zshrcPath/index" ]] && source $file
done

source "$HOME/.dotfiles/zshrc/index"

## PRIV-CONFIG
# todo make this a gitignored folder that priv-config symlinks into instead
[[ -f $HOME/Projects/priv-config/devices/macbook_pro/.zshrc ]] && source $HOME/Projects/priv-config/devices/macbook_pro/.zshrc