#!/bin/zsh

alias dot-update="$HOME/.dotfiles/dot-update"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias l!="spinner"

alias sleep="l! sleep"
alias cp="SPINNER=7 l! cp"
alias mv="SPINNER=19 l! mv"
alias rm="SPINNER=30 l! rm"
alias tar="SPINNER=18 l! tar"

iap-cd() { cd `iap-which-app $@` }
iap-code() { code `iap-which-app $@` }

alias i="[[ -e ./bunfig.toml ]] && bun i || npm i"
alias i!="[[ -e ./package.json ]] && rm -rf ./node_modules && i"
alias ci="[[ -e ./bunfig.toml ]] && bun i --frozen-lockfile || npm ci"

alias npm-nexus="cp ~/.npmrc.nexus ~/.npmrc"
alias npm-jfrog="cp ~/.npmrc.jfrog ~/.npmrc"

nlt() { jq '.packages | to_entries[] | select(.key | test("/'${1}'$")) | [.value.version, .key] | join(" -- ")' ./package-lock.json }

alias perms="stat -f '%A - %N'"

# IP addresses
# alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
# alias localip="ipconfig getifaddr en0"
# alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

alias arps='sudo arp-scan -l'

alias dirty='watch -n1 "cat /proc/meminfo | grep Dirty"'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"
alias r!="reload"

alias c!="clear"

alias :q="exit"

calc() { echo "$@" | bc -l }

alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"

alias file-download='curl --continue-at - --location --progress-bar --remote-name --remote-time'

alias rm-rf='rm -rf'

alias git-reset="git reset --hard @{upstream}"

alias port-ls="sudo lsof -iTCP -sTCP:LISTEN -n -P"

git-s() { git status --porcelain }

git-stash-patch() { git stash show "stash@{0}" -p "${1:-"stash"}.patch" }

git-nah() {
	git reset --hard
	git clean -df
	if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
		git rebase --abort
	fi
}

git-latest() {
	git fetch
	git reset --hard @{upstream}
	git clean -df
	git pull
}

vissh() { [ "$1" == "" ] && nano $HOME/.ssh/config || nano $HOME/.ssh/config.d/$1 }
vigit() { git config -e }

mkd() { mkdir -p "$@" && cd "$_" }

cmd_exists() {
	command -v "$1" &> /dev/null
}

kill_all_subprocesses() {
	local i=""

	for i in $(jobs -p); do
		kill "$i"
		wait "$i" &> /dev/null
	done
}

alias stats='sort | uniq -c | sort -r'

alias git-stats='git log --no-merges --pretty=format:"%ae" | stats'
# Lists the ten most used commands.
alias history-stats="history 0 | awk '{print \$2}' | stats | head"

# 4 lulz.
hax() {
  while true; do head -n 100 /dev/urandom; sleep 0.1; done \
    | hexdump -C | grep "ca fe"
}

holdPlz() {
	yes "say Your call is very important to ${2:-$USER}. Your patience is appreciated; sleep ${1:-"2"}" | zsh
}

# Simple .tar archiving.
tar_() { tar -cvf "$1.tar" "$1" }

untar() { tar -xvf $1 }