#!/bin/zsh

source "$HOME/.dotfiles/theme/ls.zsh"

# ls defaults
alias ls="command ls -G"

# List all files in long format
alias l="ls -lF"

# List all files in long format, excluding . and ..
alias la="ls -lAF"

# List only directories
alias lsd="ls -lF | grep --color=never '^d'"
