#!/bin/zsh

[[ -o interactive ]] || return
[[ -n "$CLAUDECODE" ]] && return

mkdir() {
	command mkdir "$@" || return
	local last=${@[-1]}
	[[ $# -gt 0 && $last != -* && $last != /* && $last != \~* ]] && cd "$last"
	return 0
}
