#!/bin/zsh

alias npmi='npm i'
alias npmstart='npm start'
alias npm-='npm run'
alias npm-ls="jq -r '.scripts | keys[]' ./package.json"
alias npm-packlist="npm pack && tar -xvzf *.tgz && rm -rf package *.tgz"
