#!/bin/zsh

alias npmi='npm i'
alias npmstart='npm start'
alias npm-='npm run'
alias npm-ls="jq -r '.scripts | keys[]' ./package.json"
alias npm-packlist="npm pack && tar -xvzf *.tgz && rm -rf package *.tgz"

if type compdef &>/dev/null; then
	_npm_completion() {
		local si=$IFS
		compadd -- $(COMP_CWORD=$((CURRENT - 1)) \
			COMP_LINE=$BUFFER \
			COMP_POINT=0 \
			npm completion -- "${words[@]}" \
			2>/dev/null)
		IFS=$si
	}
	compdef _npm_completion npm
fi