#!/bin/zsh

export NVM_DIR="$HOME/.nvm"

# Put the default node on PATH without paying nvm.sh's ~2s startup cost:
# resolve the alias file against installed versions directly
if [[ -r "$NVM_DIR/alias/default" && -d "$NVM_DIR/versions/node" ]]; then
  _nvm_default=$(<"$NVM_DIR/alias/default")
  _nvm_match=$(command ls "$NVM_DIR/versions/node" | grep "^v${_nvm_default#v}" | sort -V | tail -1)
  [[ -n "$_nvm_match" ]] && export PATH="$NVM_DIR/versions/node/$_nvm_match/bin:$PATH"
  unset _nvm_default _nvm_match
fi

# Lazy-load: the real nvm.sh is only sourced on first invocation
nvm() {
  unfunction nvm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  nvm "$@"
}
