#!/bin/zsh

vscode-install() {
  code --install-extension --force "$1"

  code --list-extensions > $HOME/.dotfiles/vscode/extensions
}

vscode-uninstall() {
  code --uninstall-extension --force "$1"

  code --list-extensions > $HOME/.dotfiles/vscode/extensions
}

vscode-update() {
  echo "Updating/Installing extensions"
  for extension in `cat $HOME/.dotfiles/vscode/extensions`; code --install-extension --force "$extension"

  code --list-extensions > $HOME/.dotfiles/vscode/extensions
}