brew "kubectl"
brew "awscli"
brew "glab"
brew "go"
# HTTPS in front of paude for the phone on the couch (dot-update.d/paude starts it, with its own Caddyfile)
brew "caddy"

cask "temurin@25"

cask "figma"
cask "lastpass"
cask "slack"
cask "microsoft-outlook"
cask "webex"
cask "docker-desktop"
cask "firefox"
cask "mongodb-compass"
