#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

echo "Linking pam sudo config"
sudo ln -sf $profilePath/pam_sudo /etc/pam.d/sudo

$macosPath/dot-update

(cd $profilePath ; brew bundle --no-lock)

$dotfilesPath/macos/macos.config.d/ssd
$dotfilesPath/macos/macos.config.d/touch-bar