tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"

# Misc
brew "thefuck"
brew "fontconfig"
brew "imagemagick"
brew "xclip"
brew "arp-scan"
brew "bat"
brew "coreutils"
brew "readline"
brew "jq"
brew "tree"
brew "svn"


# Fonts
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-fontawesome"
cask "font-hack-nerd-font"

# Misc Casks
cask "robo-3t"
cask "figma"
cask "docker"
cask "firefox"
cask "gimp"
cask "postman"
cask "mongodb-compass"
cask "visual-studio-code"
cask "google-chrome"
cask "kitty"
cask "logitech-options"
cask "logitech-unifying"