#!/bin/zsh

[[ ! -e $HOME/.dotfiles ]] && ln -sf `pwd` $HOME/.dotfiles

[[ -e $HOME/.dotfiles/dot-update.d/0_setup ]] && $HOME/.dotfiles/dot-update.d/0_setup $@

echo "Fetching latest dotfiles"
(cd $HOME/.dotfiles ; git pull)

for file in $HOME/{.,.dotfiles/}dot-update.d/*; . "$file"
