#!/bin/zsh

[[ ! -e $HOME/.dotfiles ]] && ln -sf `readlink -f ./` $HOME/.dotfiles

[[ -e ./dot-update.d/0_setup ]] && ./dot-update.d/0_setup $@

echo "Fetching latest dotfiles"
(cd $HOME/.dotfiles ; git pull)

for file in $HOME/{.,.dotfiles/}dot-update.d/*; . "$file"
