#!/bin/bash

USER_FOLDER=/home/$USER

if [ ! -e $USER_FOLDER/.config/device ]; then
  if [ $1 ]; then
		if [ ! -e ./devices/$1 ]; then
			echo "$1 is not a valid device"
		else
			DEVICE=$1
			FIRST=first

			echo $DEVICE > $USER_FOLDER/.config/device
		fi
	else
		echo "No device defined"
	fi
else
	DEVICE=$(cat $USER_FOLDER/.config/device)
fi

notify-send "Updating apt packages, may take a while..."

sudo apt update && sudo apt upgrade -y && notify-send "Success!" "Updated apt packages"

if [ "$FIRST" == "first" ]; then
	mkdir -p $USER_FOLDER/Pictures/Wallpapers $USER_FOLDER/Pictures/Screenshots $USER_FOLDER/Projects

	# Install base apps
	sudo apt install -y curl xinit xserver-xorg i3 feh dconf uuid-runtime gnome-terminal libnotify-bin

	# Purge unused apps
	sudo apt purge -y totem

	if [ ! -e /etc/apt/sources.list.d/vscode.list ]; then
		# Install vscode prerequisites
		curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
		sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
		sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
	fi

	export NVM_DIR="$HOME/.nvm"

	if [ ! -e $NVM_DIR ]; then
		# Install nvm
		curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

		[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

		nvm install --lts

		sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
		sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
	fi

	sudo gpasswd -a $USER input

	git config --global credential.helper cache
	git config --global credential.helper 'cache --timeout=3600'

	(cd ./gnome-terminal && ./SETUP)
	(cd ./fonts && ./SETUP)

	cp ./etc/gtk_dark_preference $USER_FOLDER/.config/gtk-3.0/settings.ini

	# install sudo config
	sudo cp ./etc/sudo.conf /etc/

	sudo adduser $USER dialout
fi

cat ./etc/.bashrc >> $USER_FOLDER/.bashrc

# Install apps
sudo apt install -y libinput-tools xdotool wmctrl build-essential make cpanminus autoconf automake xautolock pavucontrol leafpad xbacklight speedtest-cli xclip code default-jre gimp gpick openssh-server ffmpeg arp-scan scrot youtube-dl ruby vlc mpv dnsmasq mongodb cu net-tools libcanberra-gtk-module libcanberra-gtk3-module

(cd ./devices/$DEVICE && cp ./.profile $USER_FOLDER/)
(cd ./devices/$DEVICE && cp ./.wallpaper_subreddits $USER_FOLDER/Pictures/Wallpapers/.subreddits)

(cd ./scripts && ./SETUP)
(cd ./dunst && ./SETUP)
(cd ./i3 && ./SETUP)

(cd ./devices/$DEVICE && ./SETUP $FIRST)

if [ "$FIRST" == "first" ]; then
	echo -e "\nReady to reboot. [enter] to continue."

	read -p ""

	sudo shutdown -r now
fi