#!/bin/bash

if [ ! -e ~/.config/device ]; then
  if [ $1 ]; then
		if [ ! -e ./devices/$1 ]; then
			echo "$1 is not a valid device"
		else
			DEVICE=$1
			echo $DEVICE > ~/.config/device
			(cd ./devices/$DEVICE && ./SETUP first)
		fi
	else
		echo "No device defined"
	fi
else
	DEVICE=$(cat ~/.config/device)
  (cd ./devices/$DEVICE && ./SETUP)
fi