#!/bin/bash

if [ ! -e "$HOME/.nvm" ]; then
		# Install nvm
		curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

		export NVM_DIR="$HOME/.nvm"

		[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

		nvm install --lts

		sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
		sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
fi