#!/bin/bash

dotfiles_folder=$HOME/Projects/dotfiles

mkdir -p $HOME/.themes $HOME/.icons

cp -r $dotfiles_folder/gtk_theme/theme/Tomorrow_Night $HOME/.themes/
cp -r $dotfiles_folder/gtk_theme/cursor/Hackneyed $HOME/.icons/

gsettings set org.gnome.desktop.interface gtk-theme "Tomorrow_Night"