#!/bin/bash

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_theme \
  <(echo) ~/dotfiles/devices/work_tower/i3/_variables \
  <(echo) ~/dotfiles/devices/work_tower/i3/config \
  <(echo) ~/dotfiles/i3/config \
  <(echo) ~/dotfiles/i3/i3bar \
  <(echo) ~/dotfiles/i3/i3bar2 \
  <(echo) ~/dotfiles/i3/modes \
  <(echo) ~/dotfiles/devices/work_tower/i3/startup \
> ~/.i3/config

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_status_theme \
  <(echo) ~/dotfiles/i3/_status_items \
  <(echo) ~/dotfiles/devices/work_tower/i3/_status_order \
> ~/.i3/status.conf

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_status_theme \
  <(echo) ~/dotfiles/i3/_status_items \
  <(echo) ~/dotfiles/devices/work_tower/i3/_status2_order \
> ~/.i3/status2.conf

cp ~/dotfiles/scripts/getWindowCriteria ~/.i3/
cp ~/dotfiles/scripts/ledCtl ~/.scripts/
cp ~/dotfiles/scripts/system ~/.scripts/

i3-msg reload