#!/bin/bash

export apps=(
	"nautilus -w"
	"nautilus -w"
	"nautilus -w $HOME/Downloads"
	"gnome-terminal --working-directory $HOME"
	"gnome-terminal --working-directory $HOME/Projects"
	"gnome-terminal --working-directory $HOME/Projects"
	"gnome-terminal --working-directory $HOME/Projects"
	"code -n Projects/lib.code-workspace"
	"code -n Projects/werk.code-workspace"
	"google-chrome -d https://outlook.office365.com/owa/#path=/mail"
)

export workspaces=(
	"12"
	"12"
	"12"
	"11"
	"11"
	"11"
	"11"
	"10"
	"2"
	"1"
)

export workspaceNames=(
	"12 Files"
	"12 Files"
	"12 Files"
	"11 Term"
	"11 Term"
	"11 Term"
	"11 Term"
	"10 Lib"
	"2 Werk"
	"1 Web"
)

export workspaceColors=(
	"#8abeb7"
	"#8abeb7"
	"#8abeb7"
	"#b5bd68"
	"#b5bd68"
	"#b5bd68"
	"#b5bd68"
	"#f0c674"
	"#de935f"
	"#cc6666"
)