#!/bin/bash
if [ ! -e $HOME/.config/device ]; then
	echo "No valid device file!"
	exit 1
fi

device=$(cat $HOME/.config/device)
dotfiles_folder=$HOME/Projects/dotfiles
device_folder=$dotfiles_folder/devices/$device

if [ "$1" == "first" ]; then
	sudo cp $device_folder/etc/grub /etc/default/ && sudo update-grub2
fi

cd $HOME/Projects/htpc-remote && git pull && rm -rf node_modules && npm i

cd $HOME/Projects/home-page && git pull && rm -rf node_modules && npm i