#!/bin/bash

cd ~/dotfiles && git pull

if [ "$1" == "full" ]; then
  sudo cp ~/dotfiles/devices/htpc/etc/grub /etc/default/ && sudo update-grub2

  cp ~/dotfiles/devices/htpc/.xinitrc ~/

  ~/dotfiles/devices/htpc/xorg/update
  
  cp ~/dotfiles/devices/htpc/.wallpaper_subreddits ~/Pictures/Wallpapers/.subreddits
fi

~/dotfiles/devices/htpc/i3/update