#!/bin/bash

dconfdir=/org/gnome/terminal/legacy/profiles:

dconf reset -f $dconfdir/

new_id="$(uuidgen)"
list="['$new_id']"

dconf write $dconfdir/list "$list"
dconf write "$dconfdir/:$new_id"/visible-name "'Tomorrow_Night'"

dconf load $dconfdir/:$new_id/ < ./Tomorrow_Night.dconf

dconf write $dconfdir/default "'$new_id'"
