#!/bin/bash

dconfdir=/org/gnome/terminal/legacy/profiles:

create_new_profile() {
  local profile_ids=($(dconf list $dconfdir/ | grep ^: | sed 's/\///g' | sed 's/://g'))
  local profile_name="$1"
  local profile_ids_old="$(dconf read "$dconfdir"/list | tr -d "]")"
  local profile_id="$(uuidgen)"

  [ -z "$profile_ids_old" ] && local lb="["  # if there's no `list` key
  [ ${#profile_ids[@]} -gt 0 ] && local delimiter=,  # if the list is empty
  dconf write $dconfdir/list \
      "${profile_ids_old}${delimiter} '$profile_id']"
  dconf write "$dconfdir/:$profile_id"/visible-name "'$profile_name'"
  echo $profile_id
}

id=$(create_new_profile Tomorrow_Night)

dconf load $dconfdir/:$id/ < ./Tomorrow_Night.dconf

dconf write $dconfdir/default "'$id'"