#!/bin/bash

dotfiles_folder=$HOME/Projects/dotfiles
dconf_folder=/org/gnome/terminal/legacy/profiles:

dconf reset -f $dconf_folder/

new_id="$(uuidgen)"
list="['$new_id']"

dconf write $dconf_folder/list "$list"
dconf write "$dconf_folder/:$new_id"/visible-name "'Tomorrow_Night'"

dconf load $dconf_folder/:$new_id/ < $dotfiles_folder/gnome-terminal/Tomorrow_Night.dconf

dconf write $dconf_folder/default "'$new_id'"
