#!/bin/zsh

# Homebrew
[[ -d /home/linuxbrew/.linuxbrew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Ubuntu dotfiles Bin
export PATH="$HOME/.dotfiles/ubuntu/bin:$PATH"

# GNU Coreutils Bin
# export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
