#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

[[ "$SHELL" = "/bin/zsh" ]] || chsh -s /bin/zsh

# TODO switch over to skhdrc
# echo "Linking skhd config"
# ln -sf $profilePath/.skhdrc $HOME/.skhdrc

echo "Expanding file limits"

ulimit -Sn unlimited
ulimit -Sl unlimited

echo "Purgeing unwanted default apt packages"

$ubuntuPath/bin/apt-autopurge totem thunderbird

for file in $ubuntuPath/dot-update.d/*; source $file