#!/bin/bash

export DOTFILES=$(cd $(dirname $(readlink -f $0))/.. && pwd)

groupsToAdd="input dialout"

echo "Adding $USER to groups: $groupsToAdd"

for group in $groupsToAdd; do
	sudo adduser $USER $group
done

echo "Adding $USER to sudoers"
sudo mkdir -p /etc/sudoers.d
echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/010_$USER-nopasswd"

echo "Expanding file limits"

ulimit -Sn unlimited
ulimit -Sl unlimited

echo "Configuring cron"
sudo ln -sf $DOTFILES/cron/crontab /etc/crontab

files=$(find $DOTFILES/cron/hourly/* -type f)

for file in $files; do
	sudo ln -sf $file /etc/cron.hourly/$(basename $file)
done

files=$(find $DOTFILES/cron/daily/* -type f)

for file in $files; do
	sudo ln -sf $file /etc/cron.daily/$(basename $file)
done

if [ ! -s "$DOTFILES/temp/.gitSetup" ]; then
	echo "Setting up git"

	read -p "Enter your git user.name: " username; git config --global user.name $username
	read -p "Enter your git user.email: " email; git config --global user.email $email

	git config --global credential.helper cache
	git config --global credential.helper 'cache --timeout=3600'

	echo "1" > $DOTFILES/temp/.gitSetup
fi

apt-autoupdate

if [ ! -s "$HOME/.nvm" ]; then
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

	export NVM_DIR="$HOME/.nvm"

	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

	nvm install --lts

	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"

	npm=/usr/local/bin/npm

	sudo setcap 'cap_net_bind_service=+ep' `readlink -f /usr/local/bin/node`
fi

echo "Cleaning apt packages"

sudo apt autoremove --purge -y

sudo apt clean

notify-send "Done updating system!"

echo -e "\nPress enter to reboot now OR Press Ctrl+c to quit and reboot later\n"

read -p ""

sudo reboot