#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

if [[ ! -a $HOME/.nvm ]]; then
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
fi

source "$dotfilesPath/.zshrc.d/nvm"

$binPath/nvm-use ${GLOBAL_NODE_VERSION:-lts/*}