#!/bin/zsh

[[ `git config --global user.name` = "" ]] && {
	echo "Setting up global git username"

	read -p "username?Enter your git user.name: "; git config --global user.name $username
}

[[ `git config --global user.email` = "" ]] && {
	echo "Setting up global git email"

	read -p "email?Enter your git user.email: "; git config --global user.email $email

	git config --global credential.helper cache
	git config --global credential.helper 'cache --timeout=3600'
}