#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

# if [[ ! -a $HOME/Projects/home-page ]]; then
# 	echo "Installing home-page"

# 	(
# 		cd $HOME/Projects

# 		git clone https://github.com/fatlard1993/home-page

# 		cd $HOME/Projects/home-page

# 		npm i

# 		pm2 start --name home-page ./src/server/index.js

# 		pm2 save
# 	)
# else
# 	echo "Updating home-page"

# 	(
# 		pm2 stop home-page

# 		cd $HOME/Projects/home-page

# 		git pull

# 		rm -rf ./node_modules

# 		npm i

# 		pm2 start home-page

# 		pm2 save
# 	)
# fi