#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

mkdir -p $HOME/.vscode

echo "Linking vscode argv config"
ln -sf $dotfilesPath/vscode/argv.json $HOME/.vscode/

echo "Linking vscode settings config"
ln -sf $dotfilesPath/vscode/settings.json $HOME/.vscode/

echo "Linking vscode keybinds config"
ln -sf $dotfilesPath/vscode/keybinds.json $HOME/.vscode/

code-ext-restore