#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

echo "Linking zsh config"

ln -sf $profilePath/.zshenv $HOME/.zshenv
ln -sf $profilePath/.zshrc $HOME/.zshrc
ln -sf $profilePath/.zprofile $HOME/.zprofile
