#!/bin/bash

projectDir=/home/chase/Projects/dotfiles
homeDir=/home/chase

mkdir $homeDir/.i3 $homeDir/.scripts

cp $projectDir/i3/config $homeDir/.i3/
cp $projectDir/i3/status.conf $homeDir/.i3/
cp $projectDir/i3/getWindowCriteria $homeDir/.i3/

cp $projectDir/scripts/system $homeDir/.scripts/