#!/bin/bash

USER_FOLDER=/home/$USER

if [ ! -e $USER_FOLDER/.config/device ]; then
  echo "No valid device file!"
  exit 1
fi

DEVICE=$(cat $USER_FOLDER/.config/device)

mkdir -p $USER_FOLDER/.config/i3

cat ../etc/_fileWarning \
  <(echo) ../i3/_theme \
  <(echo) ../i3/_variables \
  <(echo) ../devices/$DEVICE/i3/_variables \
  <(echo) ../i3/_config \
  <(echo) ../devices/$DEVICE/i3/_config \
  <(echo) ../i3/_shortcuts \
  <(echo) ../devices/$DEVICE/i3/_shortcuts \
  <(echo) ../i3/_modes \
  <(echo) ../devices/$DEVICE/i3/_modes \
  <(echo) ../i3/_startup \
  <(echo) ../devices/$DEVICE/i3/_startup \
  <(echo) ../i3/_i3bar \
> $USER_FOLDER/.config/i3/config

cat ../etc/_fileWarning \
  <(echo) ../i3/_status_theme \
  <(echo) ../i3/_status_items \
  <(echo) ../devices/$DEVICE/i3/_status_order \
> $USER_FOLDER/.config/i3/status.conf

if [ -e ../devices/$DEVICE/i3/_status2_order ]; then
  cat ../etc/_fileWarning \
    <(echo) ../i3/_status_theme \
    <(echo) ../i3/_status_items \
    <(echo) ../devices/$DEVICE/i3/_status2_order \
  > $USER_FOLDER/.config/i3/status2.conf

  cat <(echo) ../i3/_i3bar2 >> $USER_FOLDER/.config/i3/config
fi

i3-msg restart