#!/bin/bash

projectDir=/home/chase/Projects/dotfiles
homeDir=/home/chase

mkdir $homeDir/.i3 $homeDir/.scripts

cat $projectDir/.warning $projectDir/i3/defaultSettings $projectDir/i3/config > $homeDir/.i3/config
cp $projectDir/i3/status.conf $homeDir/.i3/

cp $projectDir/scripts/getWindowCriteria $homeDir/.i3/
cp $projectDir/scripts/system $homeDir/.scripts/

i3-msg restart