#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"
	CMD="$(dirname $(readlink -f $0))/$(basename $0) $@"
	exec sudo $CMD
	exit #?
fi

cp ./etc/dnsmasq.conf /etc/
cp ./etc/resolv.personal /etc/
cp ./etc/resolv.conf /etc/
cp ./etc/hosts.adblock /etc/

cp ./etc/NetworkManager.conf /etc/NetworkManager/

service dnsmasq restart