#!/bin/zsh

###############################################################################
# Google Chrome                                                               #
###############################################################################

# Use the system-native print preview dialog
defaults write com.google.Chrome DisablePrintPreview -bool true

# Expand the print dialog by default
defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true

# Disable hardware acceleration (was a manual step in macos/README.md)
defaults write com.google.Chrome HardwareAccelerationModeEnabled -bool false