#!/bin/zsh

###############################################################################
# Energy saving                                                               #
###############################################################################

# Enable lid wakeup
sudo pmset -a lidwake 1

# Restart automatically on power loss
sudo pmset -a autorestart 1

# Restart automatically if the computer freezes
systemsetup -setrestartfreeze on

# Set the display sleep
sudo pmset -a displaysleep 10

# Disable machine sleep while charging
sudo pmset -c sleep 0

# Set machine sleep on battery
sudo pmset -b sleep 15

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400