#!/bin/zsh

###############################################################################
# Keyboard                                                                    #
###############################################################################

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 6
defaults write NSGlobalDomain InitialKeyRepeat -int 25

# Automatically illuminate built-in MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true
# Turn off keyboard illumination when computer is not used for 5 minutes
defaults write com.apple.BezelServices kDimTime -int 300


# \u200b = disabled

# defaults write -g NSUserKeyEquivalents -dict-add "Menu Item" -string "@$~^k"

# defaults write -g NSUserKeyEquivalents '{
# "Minimize"="\u200b";
# "Minimize All"="\u200b";
# }'

# defaults write com.apple.finder NSUserKeyEquivalents '{
# "Show Package Contents"="@\r";
# "Tags..."="@t";
# }'

# defaults write -app Safari NSUserKeyEquivalents '{
# "Show Previous Tab"="@j";
# "Show Next Tab"="@k";
# "Mail Contents of This Page"="\u200b";
# }'

# defaults write -app Mail NSUserKeyEquivalents '{
# "\033Format\033Indentation\033Decrease"="^\Uf702";
# "\033Format\033Indentation\033Increase"="^\Uf703";
# }'