#!/bin/zsh

###############################################################################
# Keyboard                                                                    #
###############################################################################

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 6
defaults write NSGlobalDomain InitialKeyRepeat -int 25

# Automatically illuminate built-in MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true
# Turn off keyboard illumination when computer is not used for 5 minutes
defaults write com.apple.BezelServices kDimTime -int 300

###############################################################################
# Mission Control: switch to desktop N with CMD+N                             #
###############################################################################

# Was a manual step in macos/README.md (System Settings > Keyboard > Shortcuts >
# Mission Control). skhd doesn't cover this - .skhdrc only has yabai's
# `space --balance`, not switch-to-space-by-number - so it stays a macOS-level
# shortcut.
#
# AppleSymbolicHotKeys IDs 118-127 are desktops 1-10. `parameters` is
# [ascii, keycode, modifier mask]; 1048576 is command. Desktop 10 gets CMD+0.
#
# CMD+1 through CMD+9 and CMD+0 land as configured. If a future macOS
# release changes the expected shape here, `defaults delete
# com.apple.symbolichotkeys AppleSymbolicHotKeys` resets every symbolic
# hotkey to its default and you can set them by hand. Needs actual Spaces
# to switch to - macOS starts a
# fresh machine with only one; add more via Mission Control (Control+Up,
# then the + in the top-right).
asciiCodes=(49 50 51 52 53 54 55 56 57 48)
keyCodes=(18 19 20 21 23 22 26 28 25 29)

for i in {1..10}; do
	defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add $((117 + i)) "
		<dict>
			<key>enabled</key><true/>
			<key>value</key><dict>
				<key>parameters</key>
				<array>
					<integer>${asciiCodes[$i]}</integer>
					<integer>${keyCodes[$i]}</integer>
					<integer>1048576</integer>
				</array>
				<key>type</key><string>standard</string>
			</dict>
		</dict>"
done

unset asciiCodes keyCodes

# Without this the new hotkeys only apply after a logout.
/System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u 2> /dev/null


# \u200b = disabled

# defaults write -g NSUserKeyEquivalents -dict-add "Menu Item" -string "@$~^k"

# defaults write -g NSUserKeyEquivalents '{
# "Minimize"="\u200b";
# "Minimize All"="\u200b";
# }'

# defaults write com.apple.finder NSUserKeyEquivalents '{
# "Show Package Contents"="@\r";
# "Tags..."="@t";
# }'

# defaults write -app Safari NSUserKeyEquivalents '{
# "Show Previous Tab"="@j";
# "Show Next Tab"="@k";
# "Mail Contents of This Page"="\u200b";
# }'

# defaults write -app Mail NSUserKeyEquivalents '{
# "\033Format\033Indentation\033Decrease"="^\Uf702";
# "\033Format\033Indentation\033Increase"="^\Uf703";
# }'