brew "alerter"
brew "koekeishiya/formulae/skhd", restart_service: true
brew "koekeishiya/formulae/yabai", restart_service: true

brew "fontconfig"
cask "robo-3t"
cask "appcleaner"
cask "karabiner-elements"
cask "muzzle"
cask "keyboard-cleaner"
cask "ytmdesktop-youtube-music"
cask "raycast"
