tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "koekeishiya/formulae"

brew "alerter"
brew "koekeishiya/formulae/skhd", restart_service: true
brew "koekeishiya/formulae/yabai", restart_service: true

# Misc
brew "watch"
brew "fzf"
brew "thefuck"
brew "xclip"
brew "arp-scan"
brew "bat"
brew "coreutils"
brew "readline"
brew "jq"
brew "tree"
brew "wget"
brew "svn"
brew "fontconfig"

# Fonts
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-fontawesome"
cask "font-hack-nerd-font"

# Misc Casks
cask "appcleaner"
cask "karabiner-elements"
cask "muzzle"
cask "keyboard-cleaner"
cask "ytmdesktop-youtube-music"
cask "raycast"
cask "gimp"
cask "postman"
cask "visual-studio-code"
cask "google-chrome"
cask "kitty"