#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

obtainSudo

echo "Installing XCode command line tools..."
if xcode-select --print-path &>/dev/null; then
	echo "XCode command line tools already installed."
elif xcode-select --install &>/dev/null; then
	echo "Finished installing XCode command line tools."
else
	echo "Failed to install XCode command line tools."
fi

(cd $macosPath ; brew bundle --no-lock)

echo "Linking karabiner config"
mkdir -p $HOME/.config/karabiner
ln -sf $macosPath/karabiner.json $HOME/.config/karabiner/karabiner.json

if [ ! -e $HOME/Library/KeyBindings/DefaultKeyBindings.dict ]; then
	echo "Linking DefaultKeyBindings"
	mkdir -p $HOME/Library/KeyBindings
	sudo ln -sf $macosPath/DefaultKeyBindings.dict $HOME/Library/KeyBindings/DefaultKeyBindings.dict
fi

echo "Linking skhd config"
ln -sf $profilePath/.skhdrc $HOME/.skhdrc

echo "Linking yabai config"
ln -sf $profilePath/.yabairc $HOME/.yabairc

echo "Setting up yabai"
sudo yabai --uninstall-sa
sudo yabai --install-sa

brew services restart skhd
brew services restart yabai

yabai --load-sa

echo "Updating mac software"
sudo softwareupdate -i -a

echo "Configuring macos"
source "$dotfilesPath/macos/macos.config.d/index"
