#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

obtainSudo

echo "Installing XCode command line tools..."
if xcode-select --print-path &>/dev/null; then
	echo "XCode command line tools already installed."
elif xcode-select --install &>/dev/null; then
	echo "Finished installing XCode command line tools."
else
	echo "Failed to install XCode command line tools."
fi

(cd $macosPath ; brew bundle --no-lock)

echo "Linking karabiner config"
mkdir -p $HOME/.config/karabiner/assets/complex_modifications
cp $macosPath/karabiner.json $HOME/.config/karabiner/karabiner.json
cp $macosPath/karabiner_complex_mods.json $HOME/.config/karabiner/assets/complex_modifications/dotfiles.json

echo "Linking kitty config"

mkdir -p $HOME/.config/kitty
ln -sf $macosPath/kitty.conf $HOME/.config/kitty/kitty.conf


if [ ! -e $HOME/Library/KeyBindings/DefaultKeyBindings.dict ]; then
	echo "Linking DefaultKeyBindings"
	mkdir -p $HOME/Library/KeyBindings
	sudo ln -sf $macosPath/DefaultKeyBindings.dict $HOME/Library/KeyBindings/DefaultKeyBindings.dict
fi

echo "Linking skhd config"
ln -sf $profilePath/.skhdrc $HOME/.skhdrc

echo "Linking yabai config"
ln -sf $profilePath/.yabairc $HOME/.yabairc

echo "Setting up yabai"
sudo yabai --uninstall-sa
sudo yabai --install-sa

brew services restart skhd
brew services restart yabai

yabai --load-sa

echo "Updating mac software"
sudo softwareupdate --all --install --force

echo "Configuring macos"
source "$dotfilesPath/macos/macos-config"

echo "Linking Java Bindings into Java Extensions"
sudo mkdir -p /Library/Java/Extensions
sudo ln -s /usr/local/lib/libsvnjavahl-1.dylib /Library/Java/Extensions/libsvnjavahl-1.dylib