#!/bin/zsh

[[ ! -s "$HOME/.nvm" ]] && {
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

	export NVM_DIR="$HOME/.nvm"

	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

	nvm install --lts

	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"

	npm=/usr/local/bin/npm

	sudo setcap 'cap_net_bind_service=+ep' `readlink -f /usr/local/bin/node`
}