#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

[[ ! -s /etc/apt/trusted.gpg.d/packages.microsoft.gpg ]] && {
	# Install vscode prerequisites
	sudo apt install -y wget gpg apt-transport-https

	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/packages.microsoft.gpg > /dev/null
}

[[ ! -s /etc/apt/sources.list.d/vscode.list ]] && {
	sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
}

mkdir -p $HOME/.config/Code/User

echo "Linking vscode settings config"
ln -sf $dotfilesPath/vscode/settings.json $HOME/.config/Code/User/

echo "Linking vscode keybinds config"
ln -sf $dotfilesPath/vscode/keybindings.json $HOME/.config/Code/User/
