#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"

	exec sudo $(dirname $(readlink -f $0))/$(basename $0) $@

	exit #?
fi

dotfiles_folder=$HOME/Projects/dotfiles

cp $dotfiles_folder/cron/crontab /etc/
cp $dotfiles_folder/cron/hourly/* /etc/cron.hourly/
cp $dotfiles_folder/cron/daily/* /etc/cron.daily/