#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

echo "Linking karabiner config"
mkdir -p $HOME/.config/karabiner/assets/complex_modifications
ln -sf $macosPath/karabiner.json $HOME/.config/karabiner/karabiner.json
ln -sf $macosPath/karabiner_complex_mods.json $HOME/.config/karabiner/assets/complex_modifications/dotfiles.json
