#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

echo "Linking DefaultKeyBinding"

mkdir -p $HOME/Library/KeyBindings
ln -sf $macosPath/DefaultKeyBinding.dict $HOME/Library/KeyBindings/DefaultKeyBinding.dict
