#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

echo "Configuring macos"
source "$macosPath/macos-config"

echo "Updating mac software"
obtainSudo
sudo softwareupdate --all --install --force
