#!/bin/zsh

pgrep -f "wallpaper get" > /dev/null || $HOME/.dotfiles/ubuntu/bin/wallpaper get 15 &

pgrep -f "wallpaper-per-desktop" > /dev/null || $HOME/.dotfiles/ubuntu/bin/wallpaper-per-desktop &

pgrep -f "wallpaper-hourly-rotate" > /dev/null || $HOME/.dotfiles/ubuntu/bin/wallpaper-hourly-rotate &