#!/bin/zsh

###############################################################################
# SSD-specific tweaks                                                         #
###############################################################################

# Disable hibernation (speeds up entering sleep mode)
pmset -a hibernatemode 0

# Remove the sleep image file to save disk space
rm /private/var/vm/sleepimage
# Create a zero-byte file instead…
touch /private/var/vm/sleepimage
# …and make sure it can’t be rewritten
chflags uchg /private/var/vm/sleepimage

# Disable the sudden motion sensor as it’s not useful for SSDs
pmset -a sms 0
