#!/bin/zsh

###############################################################################
# MacBookPro Touch Bar                                                        #
###############################################################################

# Always display full control strip (ignoring App Controls)
# defaults write com.apple.touchbar.agent PresentationModeGlobal fullControlStrip