#!/bin/zsh

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd.='cd $(readlink -f .)'    # Go to real dir (i.e. if current dir is linked)

alias perms="stat -f '%A - %N'"

# Change working directory to the top-most Finder window location
alias cdf='function __cdf() { cd `osascript -e "tell app \"Finder\" to POSIX path of (insertion location as alias)"`; unset -f cdf; }; cdf'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

alias arps='sudo arp-scan -l'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

alias calc='echo "$*" | bc -l'

alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"

alias file-downlaod='curl --continue-at - --location --progress-bar --remote-name --remote-time'

alias F='fuck'

alias npmi='npm i'
alias npm-packlist="npm pack && tar -xvzf *.tgz && rm -rf package *.tgz"

mcd() { mkdir -p "$@" && cd "$_" }

cmd_exists() {
	command -v "$1" &> /dev/null
}

kill_all_subprocesses() {
	local i=""

	for i in $(jobs -p); do
		kill "$i"
		wait "$i" &> /dev/null
	done
}