#!/bin/zsh

thisPath=`dirname ${BASH_SOURCE[0]:-${(%):-%x}}`

unsetopt nomatch

fpath=($HOME/.dotfiles/zshcompletion $fpath)

# Enable completions
autoload -Uz compinit && compinit

# Support urls without quotes
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

for file in $thisPath/*(.); do
	[[ "$file" != "$thisPath/index" ]] && source $file
done

for file in $HOME/.zshrc.d/*; source $file