#!/bin/zsh

unsetopt nomatch

fpath=($HOME/.dotfiles/zshcompletion $fpath)

# Enable completions
autoload -Uz compinit && compinit

# Support urls without quotes
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

zshrcPath="$HOME/.dotfiles/zshrc"

for file in $zshrcPath/*(.); do
	[[ "$file" != "$zshrcPath/index" ]] && source $file
done

for file in $HOME/.zshrc.d/*; source $file