#!/bin/bash

if [ ! -e $HOME/.config/device ]; then
  echo "No valid device file!"
  exit 1
fi

device=$(cat $HOME/.config/device)
dotfiles_folder=$HOME/Projects/dotfiles
device_folder=$dotfiles_folder/devices/$device

if [ "$1" == "first" ]; then
	sudo cp $device_folder/etc/grub /etc/default/ && sudo update-grub2

  git config --global user.name  "fatlard1993"
  git config --global user.email "fatlard1993@gmail.com"

  cd $HOME/Projects

	git clone https://github.com/fatlard1993/swiss-army-knife
	git clone https://github.com/fatlard1993/symetrix-web-common
	git clone https://github.com/fatlard1993/touch-panel
	git clone https://github.com/fatlard1993/control-server
	git clone https://github.com/fatlard1993/control-server-mother-hub
	git clone https://github.com/fatlard1993/dsp-web-interface
	git clone https://github.com/bulletmark/libinput-gestures.git

  $HOME/Projects/swiss-army-knife/SETUP
  $HOME/Projects/symetrix-web-common/SETUP
  $HOME/Projects/touch-panel/SETUP
  $HOME/Projects/control-server/SETUP
  $HOME/Projects/control-server-mother-hub/SETUP
  $HOME/Projects/dsp-web-interface/SETUP
	cd $HOME/Projects/libinput-gestures && sudo make install && libinput-gestures-setup autostart

	$dotfiles_folder/vscode/SETUP
fi

sudo apt install -y gimp gpick code vlc mpv mongodb

cp $device_folder/libinput-gestures.conf $HOME/.config/

$device_folder/xorg/SETUP