#!/bin/bash

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

DOTFILES=$DOTFILES update-dotfiles-ubuntu
DOTFILES=$DOTFILES update-dotfiles-i3

echo "Updating grub"

sudo ln -sf $device_folder/etc/grub /etc/default/grub

sudo update-grub2

echo "Installing apt packages for $DOTFILES_DEVICE"

aptPackages="gimp gpick code vlc mpv mongodb onboard android-tools-adb"

for package in $aptPackages; do
	if [ "$(dpkg -s $package | grep Status)" != "Status: install ok installed" ]; then sudo apt install -y $package; fi
done

cp $device_folder/libinput-gestures.conf $HOME/.config/

sudo mkdir -p /etc/X11/xorg.conf.d

files=$(find $DOTFILES/devices/$DOTFILES_DEVICE/xorg/* -type f)

for file in $files; do
	sudo ln -sf $file /etc/X11/xorg.conf.d/$(basename $file)
done

ln -sf $device_folder/.profile $HOME/.profile

ln -sf $device_folder/.wallpaper_subreddits $HOME/Pictures/Wallpapers/.subreddits

if [ ! "$DOTFILES/temp/.fwupdSetup" ]; then
	sudo snap remove fwupd; sudo apt purge fwupd; sudo snap install fwupd --classic

	echo "1" > $DOTFILES/temp/.fwupdSetup
fi

fwupd.fwupdmgr get-devices
fwupd.fwupdmgr refresh
fwupd.fwupdmgr get-updates
fwupd.fwupdmgr update