#!/bin/bash

sudo cp ~/dotfiles/devices/xps_13_9360/etc/grub /etc/default && sudo update-grub2

~/dotfiles/devices/xps_13_9360/xorg/update

~/dotfiles/devices/xps_13_9360/i3/update

sudo apt update -y && sudo apt upgrade -y