#!/bin/bash

source sudo-enforce

echo "Updating apt packages"

notify-send "Updating apt packages, may take a while..."

apt update --fix-missing

dpkg --configure -a

apt upgrade -y

apt install --fix-broken -y

notify-send "Updated apt packages"