#!/bin/bash

export DOTFILES=$(cd $(dirname $(readlink -f $0))/.. && pwd)

if [ "$DOTFILES_DEVICE" ]; then
	echo "DEVICE: $DOTFILES_DEVICE"
elif [ "$1" ] && [ -d "$DOTFILES/devices/$1" ]; then
	DOTFILES_DEVICE=$1
else
	echo -e "\n\"$1\" is not a valid device. You can also provide one as an argument, eg: $0 <device>\n\n$(ls $DOTFILES/devices)\n"

	read -p "Enter the device type: " deviceType; exec $(dirname $(readlink -f $0))/$(basename $0) $deviceType

	exit #?
fi

if [ -z "$OG_PATH" ]; then
	OG_PATH=$PATH
	PATH=$DOTFILES/scripts/:$PATH
fi

export OG_PATH
export PATH
export DOTFILES_DEVICE