#!/bin/bash

mkdir -p ~/.i3

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_theme \
  <(echo) ~/dotfiles/devices/htpc/i3/_variables \
  <(echo) ~/dotfiles/devices/htpc/i3/config \
  <(echo) ~/dotfiles/i3/i3bar \
  <(echo) ~/dotfiles/devices/htpc/i3/startup \
> ~/.i3/config

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_status_theme \
  <(echo) ~/dotfiles/i3/_status_items \
  <(echo) ~/dotfiles/devices/htpc/i3/_status_order \
> ~/.i3/status.conf


i3-msg restart