#!/bin/bash

export apps=(
	"gnome-terminal"
	"nautilus -w $HOME/Downloads"
	"google-chrome"
)

export workspaces=(
	"3"
	"2"
	"1"
)

export workspaceNames=(
	"3 Term"
	"2 Files"
	"1 Web"
)

export workspaceColors=(
	"#b5bd68"
	"#8abeb7"
	"#cc6666"
)