#!/bin/bash

mkdir -p /etc/systemd/system/getty@tty1.service.d && cp ./autologin.conf /etc/systemd/system/getty@tty1.service.d/

cp ./.profile ~/

if [ "$1" == "first" ]; then
	sudo shutdown -r now
fi