#!/bin/bash

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

DOTFILES=$DOTFILES update-dotfiles-i3

echo "Installing apt packages for $DOTFILES_DEVICE"

aptPackages="xinput-calibrator matchbox-keyboard"

for package in $aptPackages; do
	if [ "$(dpkg -s $package | grep Status)" != "Status: install ok installed" ]; then sudo apt install -y $package; fi
done

cp $device_folder/libinput-gestures.conf $HOME/.config/

ln -sf $device_folder/.profile $HOME/.profile

ln -sf $device_folder/.wallpaper_subreddits $HOME/Pictures/Wallpapers/.subreddits

sudo ln -sf $device_folder/config.txt /boot/config.txt

sudo update-alternatives --config x-session-manager && update-alternatives --config x-window-manager