#!/bin/bash

if [ "$1" == "first" ]; then
	sudo cp ./etc/grub /etc/default/ && sudo update-grub2

  git config --global user.name  "fatlard1993"
  git config --global user.email "fatlard1993@gmail.com"

  cd ~/Projects && \
    git clone https://github.com/fatlard1993/swiss-army-knife && \
    git clone https://github.com/fatlard1993/symetrix-web-common && \
    git clone https://github.com/fatlard1993/touch-panel && \
    git clone https://github.com/fatlard1993/control-server && \
    git clone https://github.com/fatlard1993/control-server-mother-hub && \
    git clone https://github.com/fatlard1993/dsp-web-interface


  cd ~/Projects/swiss-army-knife && ./SETUP
  cd ~/Projects/symetrix-web-common && ./SETUP
  cd ~/Projects/touch-panel && ./SETUP
  cd ~/Projects/control-server && ./SETUP
  cd ~/Projects/control-server-mother-hub && ./SETUP
  cd ~/Projects/dsp-web-interface && ./SETUP
fi

if [ "$1" == "first" ]; then
	sudo shutdown -r now
fi