#!/bin/bash

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

update-dotfiles-ubuntu
update-dotfiles-i3

echo "Updating grub"

sudo ln -sf $device_folder/etc/grub /etc/default/grub

sudo update-grub2

echo "Installing apt packages for $DOTFILES_DEVICE"

aptPackages="gimp gpick code vlc mpv mongodb onboard android-tools-adb smbclient samba cifs-utils"

for package in $aptPackages; do
	if [ "$(dpkg -s $package | grep Status)" != "Status: install ok installed" ]; then sudo apt install -y $package; fi
done

ln -sf $device_folder/.profile $HOME/.profile

ln -sf $device_folder/.wallpaper_subreddits $HOME/Pictures/Wallpapers/.subreddits