#!/bin/bash

dotfiles_folder=$HOME/Projects/dotfiles
device=$(cat $HOME/.config/device)

if [ "$1" == "first" ]; then
	sudo cp $dotfiles_folder/devices/$device/etc/grub /etc/default/ && sudo update-grub2

	$dotfiles_folder/vscode/SETUP

  git config --global user.name  "fatlard1993"
  git config --global user.email "fatlard1993@gmail.com"

  cd $HOME/Projects

	git clone https://github.com/fatlard1993/swiss-army-knife
	git clone https://github.com/fatlard1993/symetrix-web-common
	git clone https://github.com/fatlard1993/touch-panel
	git clone https://github.com/fatlard1993/control-server
	git clone https://github.com/fatlard1993/dsp-web-interface

  $HOME/Projects/swiss-army-knife/SETUP
  $HOME/Projects/symetrix-web-common/SETUP
  $HOME/Projects/touch-panel/SETUP
  $HOME/Projects/control-server/SETUP
  $HOME/Projects/dsp-web-interface/SETUP
fi

sudo apt install -y gimp gpick vlc mpv mongodb smbclient samba cifs-utils

cd $HOME/Projects/home-page && git pull && rm -rf node_modules && npm i