#!/bin/zsh

[[ ! -a  $HOME/.local/bin/aptfile ]] && {
	echo "Installing aptfile"

	mkdir -p $HOME/.local/bin

  curl -o $HOME/.local/bin/aptfile https://raw.githubusercontent.com/seatgeek/bash-aptfile/master/bin/aptfile

	chmod +x $HOME/.local/bin/aptfile
}

echo "Installing ubuntu apps"

sudo $HOME/.dotfiles/ubuntu/aptfile

echo "Autoinstalling drivers"

sudo ubuntu-drivers autoinstall
