#!/bin/zsh

source "$HOME/.dotfiles/bin/lib/dot-util" "$0" "$@"

# echo "Installing apt packages for i3"

# apt-autoinstall i3 libnotify-bin fonts-font-awesome feh imagemagick xdotool wmctrl xautolock caffeine rofi

echo "Generating i3 config"

# if [ ! "$DOTFILES" ]; then
# 	echo "error"
# 	notify-send "$(pwd)"

# 	exit 1
# fi

mkdir -p $HOME/.config/i3

SCREEN_DIMENSIONS=`xdpyinfo | grep dimensions | sed 's/x/ /'`
SCREEN_WIDTH=`echo $SCREEN_DIMENSIONS | awk '/dimensions/{print $2}'`
SCREEN_HEIGHT=`echo $SCREEN_DIMENSIONS | awk '/dimensions/{print $3}'`

echo "set \$dotfilesPath $dotfilesPath" > /tmp/i3SysVars
echo "set \$dotfilesDevice $profileName" >> /tmp/i3SysVars
echo "set \$deviceFolder $profilePath" >> /tmp/i3SysVars
echo "set \$screenWidth $SCREEN_WIDTH" >> /tmp/i3SysVars
echo "set \$screenHeight $SCREEN_HEIGHT" >> /tmp/i3SysVars
echo "set \$overwatch floating enable, sticky enable, resize set $(( $SCREEN_WIDTH / 2 )) $(( $SCREEN_HEIGHT / 2 )), move window to position $(($SCREEN_WIDTH / 2)) 0" >> /tmp/i3SysVars

cat $ubuntuPath/i3/_theme \
	<(echo) /tmp/i3SysVars \
  <(echo) $ubuntuPath/i3/_variables \
  <(echo) $profilePath/i3/_variables \
  <(echo) $ubuntuPath/i3/_config \
  <(echo) $profilePath/i3/_config \
  <(echo) $ubuntuPath/i3/_shortcuts \
  <(echo) $profilePath/i3/_shortcuts \
  <(echo) $ubuntuPath/i3/_modes \
  <(echo) $profilePath/i3/_modes \
  <(echo) $ubuntuPath/i3/_startup \
  <(echo) $profilePath/i3/_startup \
  <(echo) $ubuntuPath/i3/_i3bar \
> $HOME/.config/i3/config

cat $ubuntuPath/i3/_status_theme \
  <(echo) $ubuntuPath/i3/_status_items \
  <(echo) $profilePath/i3/_status_order \
> $HOME/.config/i3/status.conf

if [ -s "$profilePath/i3/_status2_order" ]; then
  cat $ubuntuPath/i3/_status_theme \
    <(echo) $ubuntuPath/i3/_status_items \
    <(echo) $profilePath/i3/_status2_order \
  > $HOME/.config/i3/status2.conf

  cat <(echo) $ubuntuPath/i3/_i3bar2 >> $HOME/.config/i3/config
fi

i3-msg restart