#!/bin/zsh

echo "Adding $USER to sudoers"

sudo mkdir -p /etc/sudoers.d

echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/010_$USER-nopasswd"


echo "Bypassing sudoers secure path"

sudo sed -i -e 's/Defaults\tsecure_path/#Defaults\tsecure_path/' /etc/sudoers


[[ ! -s /etc/sudo.conf ]] && {
	echo "Generating sudo.conf"

	echo "Path askpass $DOTFILES/scripts/zenity-askpass" | sudo tee /etc/sudo.conf
}
