#!/bin/zsh

[[ ! -s /etc/apt/trusted.gpg.d/packages.microsoft.gpg ]] && {
	# Install vscode prerequisites
	sudo apt install -y wget gpg apt-transport-https

	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/packages.microsoft.gpg > /dev/null
}

[[ ! -s /etc/apt/sources.list.d/vscode.list ]] && {
	sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
}
