#!/bin/zsh

[[ ! -s /etc/apt/sources.list.d/vscode.list ]] && {
	# Install vscode prerequisites
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

	sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/

	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

	addedRepo=true
}
