#!/bin/zsh

# GNU Coreutils Bin
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Java
export JAVA_VERSION="temurin-21"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/$JAVA_VERSION.jdk/Contents/Home"
export PATH="$PATH:$JAVA_HOME/bin"