#!/bin/bash

source enforceSudo

echo "Installing apt packages"

for package in $1; do
	if [ "$(dpkg -s $package | grep Status)" != "Status: install ok installed" ]; then sudo apt install -y $package; fi
done