#!/bin/bash

source enforceSudo

notify-send "Updating apt packages, may take a while..."

dpkg --configure -a

apt update

apt upgrade -y

apt install --fix-broken --fix-missing -y

notify-send "Updated apt packages"