#!/bin/bash

source enforceSudo

echo "Purging apt packages"

for package in $1; do
	if [ "$(dpkg -s $package | grep Status)" == "Status: install ok installed" ]; then sudo apt purge -y $package; fi
done