#!/bin/bash

INCLUDES=${1:-"Arduino Documents Downloads Misc Music Pictures Projects"}
BACKUP_DEVICE=/media/$USER/MEDIA
BACKUP_LOCATION=$BACKUP_DEVICE/Backups
EXTRA_BACKUPS=2

if [ ! -e $BACKUP_LOCATION ]; then
	echo "$BACKUP_LOCATION is not available"

	exit 1
fi

if [ "$1" == "--restore" ]; then
	RESTORE_INDEX=${2:-0}
	BACKUP_LOCATION=$BACKUP_LOCATION/$DOTFILES_DEVICE/$RESTORE_INDEX

	echo "Restoring from $BACKUP_LOCATION"

	for file in $BACKUP_LOCATION/* ; do
		tar -xzvf $file -C $HOME
	done

	exit 1
fi

echo "Saving some known goodies"

cp -n $HOME/.minecraft/screenshots/* $HOME/Pictures/Screenshots/minecraft/

rsync -raz --ignore-existing --progress $HOME/Podcasts/* $BACKUP_DEVICE/Podcasts/
rsync -raz --ignore-existing --progress $HOME/Pictures/Wallpapers/stashed/* $BACKUP_DEVICE/Pictures/Misc/
rsync -raz --ignore-existing --progress $HOME/Pictures/Misc/* $BACKUP_DEVICE/Pictures/Misc/
rsync -raz --ignore-existing --progress $HOME/Pictures/Screenshots/minecraft/* $BACKUP_DEVICE/Pictures/Minecraft/

echo "Backing up your beloved files"

BACKUP_LOCATION=$BACKUP_LOCATION/$DOTFILES_DEVICE

for (( index = $EXTRA_BACKUPS; index >= 0; --index)); do
	if [ -e $BACKUP_LOCATION/$index ]; then
		if [ $index == $EXTRA_BACKUPS ]; then
			rm -rf $BACKUP_LOCATION/$index
		else
			mv $BACKUP_LOCATION/$index $BACKUP_LOCATION/$(( index + 1 ))
		fi
	fi
done

mkdir -p $BACKUP_LOCATION/0

cd $HOME

for item in $INCLUDES ; do
	tar -czvf $BACKUP_LOCATION/0/$item.tar.gz $item
done