#!/bin/bash

if [[ `whoami` != "root" ]]; then
  echo "This script needs to be run as root.."
  echo "Restarting with sudo"
  SCRIPT="$(dirname $(readlink -f $0))/$(basename $0) $@"
  echo "$SCRIPT"
  exec sudo $SCRIPT
  exit #?
fi

echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a && notify-send 'Success!' 'Ram-cache and Swap Cleared'