#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"

	exec sudo $(dirname $(readlink -f $0))/$(basename $0) $@

	exit #?
fi

echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a && notify-send 'Success!' 'Ram-cache and Swap Cleared'