#!/bin/bash

export DOTFILES=$(cd $(dirname $(readlink -f $0))/.. && pwd)

source $DOTFILES/scripts/dotfiles-variables

if [ -s /etc/bash.bashrc.bkup ]; then
	echo "Restoring default bashrc"

	sudo mv /etc/bash.bashrc.bkup /etc/bash.bashrc
fi

if [ -s "$HOME/.bashrc.bkup" ]; then
	echo "Restoring default user bashrc files"

	mv $HOME/.bashrc.bkup $HOME/.bashrc
	sudo mv /root/.bashrc.bkup /root/.bashrc
fi

if [ -s /etc/inputrc.bkup ]; then
	echo "Restoring default inputrc"

	sudo mv /etc/inputrc.bkup /etc/inputrc
fi

if [ ! -s /etc/bash.bashrc.bkup ]; then
	echo "Backing up default bashrc"
	sudo cp /etc/bash.bashrc /etc/bash.bashrc.bkup

	echo "Enabling global variables"
	echo -e "\nexport OG_PATH=\"$OG_PATH\"" | sudo tee /etc/profile.d/00_env.sh
	echo "export PATH=\"$PATH\"" | sudo tee -a /etc/profile.d/00_env.sh
	echo "export DOTFILES=$DOTFILES" | sudo tee -a /etc/profile.d/00_env.sh
	echo -e "export DOTFILES_DEVICE=$DOTFILES_DEVICE\n" | sudo tee -a /etc/profile.d/00_env.sh
	sudo chmod +x /etc/profile.d/00_env.sh
	cat /etc/profile.d/00_env.sh | sudo tee -a /etc/bash.bashrc

	echo "Bypassing sudoers secure path"
	sudo sed -i -e 's/Defaults\tsecure_path/#Defaults\tsecure_path/' /etc/sudoers

	echo "Enabling bashrc.d"
	cat $DOTFILES/etc/bashrc | sudo tee -a /etc/bash.bashrc
fi

if [ ! -s "$HOME/.bashrc.bkup" ]; then
	echo "Backing up and user bashrc files"

	cp $HOME/.bashrc $HOME/.bashrc.bkup
	sudo cp /root/.bashrc /root/.bashrc.bkup
fi

if [ ! -s /etc/inputrc.bkup ]; then
	echo "Backing up default inputrc"
	sudo cp /etc/inputrc /etc/inputrc.bkup

	echo "Extending inputrc"
	echo -e "\n\"\C-h\": backward-kill-word" | sudo tee -a /etc/inputrc
	echo -e "\"\\\e[3;5~\": kill-word\n" | sudo tee -a /etc/inputrc
fi

echo "Linking device profile"
sudo ln -sf $DOTFILES/devices/$DOTFILES_DEVICE/.profile /etc/profile.d/device.sh