#!/bin/bash

echo "Adding apt repositories"

aptRepos="maarten-baert/simplescreenrecorder"

for repo in $aptRepos; do
	if [ ! -s "/etc/apt/sources.list.d/$repo.list" ]; then
		echo "Adding repository: $repo"

		sudo add-apt-repository -y ppa:$repo

		addedRepo=true
	fi
done

if [ ! -s /etc/apt/sources.list.d/vscode.list ]; then
	# Install vscode prerequisites
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

	sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/

	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

	addedRepo=true
fi

if [ "$addedRepo" ]; then sudo apt update -y; fi

echo "Installing apt packages for ubuntu"

apt-autoinstall xinit xserver-xorg pasystray default-jre dconf-tools simplescreenrecorder code gnome-terminal nautilus libinput-tools pavucontrol leafpad xbacklight xclip scrot libcanberra-gtk-module libcanberra-gtk3-module ffmpeg rofi

echo "Autoinstalling drivers"

sudo ubuntu-drivers autoinstall

echo "Purgeing apt packages"

apt-autopurge totem thunderbird

echo "Installing global npm packages"

globalNpmPackages="npm-check-updates fatlard1993/zelda fatlard1993/skel"

for package in $globalNpmPackages; do
	npm list -g | grep $package || npm i -g $package
done

if [ ! -s "$DOTFILES/temp/.gtkSetup" ]; then
	echo "Setting gtk dark preference"

	echo -e "[Settings]\ngtk-application-prefer-dark-theme=1" > $HOME/.config/gtk-3.0/settings.ini

	echo "1" > $DOTFILES/temp/.gtkSetup
fi

if [ ! -s "$DOTFILES/temp/.rofiSetup" ]; then
	echo "Setting up rofi"

	ln -sf $DOTFILES/rofi/config $HOME/.config/rofi/config

	echo "1" > $DOTFILES/temp/.rofiSetup
fi

if [ ! -s "$DOTFILES/temp/.greenclipSetup" ]; then
	echo "Setting up greenclip"

	(
		cd /usr/local/bin

		wget https://github.com/erebe/greenclip/releases/download/3.3/greenclip

		chmod +x ./greenclip
	)

	echo "1" > $DOTFILES/temp/.greenclipSetup
fi

if [ ! -s /etc/sudo.conf ]; then
	echo "Generating sudo.conf"

	echo "Path askpass $DOTFILES/scripts/zenity-askpass" | sudo tee /etc/sudo.conf
fi

if [ ! -s "$DOTFILES/temp/.terminalSetup" ]; then
	echo "Setting up gnome-terminal"

	dconf_folder=/org/gnome/terminal/legacy/profiles:

	dconf reset -f $dconf_folder/

	new_id="$(uuidgen)"
	list="['$new_id']"

	dconf write $dconf_folder/list "$list"
	dconf write "$dconf_folder/:$new_id"/visible-name "'Tomorrow_Night'"

	dconf load $dconf_folder/:$new_id/ < $DOTFILES/etc/Tomorrow_Night.dconf

	dconf write $dconf_folder/default "'$new_id'"

	echo "1" > $DOTFILES/temp/.terminalSetup
fi

if [ ! -s "$DOTFILES/temp/.dunstSetup" ]; then
	echo "Setting up dunst"

	mkdir -p $HOME/.config/dunst

	ln -sf $DOTFILES/dunst/dunstrc $HOME/.config/dunst/ && sudo pkill dunst
fi

mkdir -p $HOME/Projects/external

if [ ! -d "$HOME/Projects/external/libinput-gestures" ]; then
	echo "Installing libinput-gestures"

	(
		cd $HOME/Projects/external

		git clone https://github.com/bulletmark/libinput-gestures.git

		cd ./libinput-gestures

		sudo make install

		libinput-gestures-setup autostart
	)
fi

dotfiles-update-fonts