#!/bin/bash

ACTIVE_WINDOW_ID=$(xprop -root | awk '/NET_ACTIVE_WINDOW/ { print $5; exit}')
ACTIVE_WINDOW_CLASS=$(xprop -id $ACTIVE_WINDOW_ID | awk -F\" '/WM_CLASS/ {print $2; exit}')

echo $ACTIVE_WINDOW_CLASS

[[ $1 == "gui" ]] && zenity --info --width=300 --text=$ACTIVE_WINDOW_CLASS