#!/bin/bash

device_folder=$DOTFILES/devices/$DOTFILES_DEVICE

source $device_folder/i3/workspace-init

openedWindows=0

for x in ${!apps[*]}; do
	while [ "$openedWindows" -lt "$x" ]; do
		openedWindows=$(wmctrl -l | wc -l)

		sleep 0.3s
	done

	i3-msg workspace number ${workspaces[$x]}

	i3-msg "rename workspace \"$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep name | cut -d\" -f 3)\" to \"${workspaces[$x]}<span foreground='${workspaceColors[$x]}' weight='heavy'>${workspaceNames[$x]}</span>\""

	eval ${apps[$x]} &
done