#!/bin/bash

OLD_LABEL=$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep name | cut -d\" -f 3)
WORKSPACE_NUM=$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep num | cut -d: -f 2)
NEW_LABEL=$(zenity --entry --text="Rename workspace:" --entry-text="")

if [[ "$NEW_LABEL" == "r" ]]; then
	i3-msg "rename workspace \"$OLD_LABEL\" to $WORKSPACE_NUM"

	exit 1
fi

NUM_REGEX='^[0-9]+$'
if [[ $NEW_LABEL =~ $NUM_REGEX ]]; then
	WORKSPACE_NUM=$NEW_LABEL

	i3-msg "rename workspace \"$OLD_LABEL\" to $WORKSPACE_NUM"

	exit 1
fi

COLOR=$(printf "#%02x%02x%02x" $(zenity --color-selection --color='#000' |sed -e 's/rgb(//' -e 's/,/ /g' -e's/)//'))

i3-msg "rename workspace \"$OLD_LABEL\" to \"$WORKSPACE_NUM<span foreground='$COLOR' weight='heavy'>$NEW_LABEL</span>\""