#!/bin/bash

help() {
	cat <<EOF
Usage:
  imageDrive [OPTIONS...]

Options:
  -?, -h, --help           Show help (this)
  -i, --image=<image>      Specifies the image input file
  -d, --device=<device>    Specifies the device output

EOF
}

while (( $# > 0 )) ; do
	case "$1" in
		-\?|-h|--help)
			help
			exit 0
		;;
		-i|--image|--image=*)
			[[ "$1" = --image=* ]] && image="${1#*=}" || { shift; image="$1"; }
		;;
		-d|--device|--device=*)
			[[ "$1" = --device=* ]] && device="${1#*=}" || { shift; device="$1"; }
		;;
		*)
			echo "Unrecgonized option .. For a full list of available options see imageDrive -h"
			exit 1
	esac
	shift
done

if [ ! "$image" ]; then
	image=`readlink -f ./*.img`
else
	image=`readlink -f $image`
fi

if [ ! "$image" ]; then
	echo -e "Could not autodetect an image. Please specify one\n imageDrive \x1b[31m-i <image>\x1b[0m"
	exit 1
fi

if [ ! "$device" ]; then
	device="/dev/$(lsblk -o NAME | grep mmc | head -n 1)";
fi

if [ "$device" = "/dev/" ]; then
	device="/dev/$(lsblk -o NAME | grep sda | head -n 1)";
fi

if [ "$device" = "/dev/" ]; then
	echo -e "Could not autodetect a device. Please specify one\n imageDrive \x1b[31m-d <device>\x1b[0m"
	exit 1
fi

lsblk | grep disk

sudo $DOTFILES/scripts/duplicateImage $image $device