#!/bin/bash

source enforceSudo

# check dependencies
command -v setxkbmap >/dev/null 2>&1 || { echo >&2 "Script requires setxkbmap but it is not installed.Aborting."; exit 1; }
command -v setleds >/dev/null 2>&1 || { echo >&2 "Script requires setleds but it is not installed.Aborting."; exit 1; }

CONSOLE=/dev/console

# indicator LED to use: caps | num | scroll
INDICATOR=$1

getVmstat(){
	egrep "pgpgin|pgpgout" /proc/vmstat
}

function led_on(){
	setleds -L +${INDICATOR} < ${CONSOLE} >/dev/null 2>&1
}

function led_off(){
	setleds -L -${INDICATOR} < ${CONSOLE} >/dev/null 2>&1
}

if [ "$2" = "0" ]; then
	led_off
elif [ "$2" = "1" ]; then
	led_on
elif [ "$2" = "monitor" ]; then
	CHECKINTERVAL=0.1
	NEW=$(getVmstat)
	OLD=$(getVmstat)

	while [ 1 ] ; do
		sleep $CHECKINTERVAL
		NEW=$(getVmstat)
		if [ "$NEW" = "$OLD" ]; then
			led_off
		else
			led_on
		fi
		OLD=$NEW
	done
else
	echo -e "\nUseage:\nledCtl num 1\nledCtl scroll 0\nledCtl caps monitor\n"
fi
