#!/bin/sh

mkdir ~/Projects

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt update -y && sudo apt install -y build-essential libssl-dev arp-scan default-jre gnome-tweak-tool curl wget

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && nvm install --lts

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg