#!/bin/sh

mkdir ~/Projects

sudo apt update -y && sudo apt install -y build-essential libssl-dev curl wget arp-scan

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && nvm install --lts

sudo apt update -y && sudo apt install -y code default-jre gnome-tweak-tool pick-colour-picker gimp openssh-server ffmpeg

cd ~/Projects && \
  git clone https://github.com/imaustink/game.git && \
  git clone https://github.com/fatlard1993/copyPasta.git

cd ~/Projects && \
  git clone https://github.com/imaustink/game.git && \
  git clone https://github.com/fatlard1993/copyPasta.git && \
  git clone https://github.com/fatlard1993/sandbox.git

cd ~/Projects && \
  git clone https://github.com/fatlard1993/symetrix-common.git && \
  git clone https://github.com/fatlard1993/control-server.git && \
  git clone https://github.com/fatlard1993/control-server-mother-hub.git && \
  git clone https://github.com/fatlard1993/unit-status.git