#!/bin/bash

projectName=$1

cd $HOME/Projects

git clone https://github.com/fatlard1993/$projectName

cd $HOME/Projects/$projectName

mkdir -p src

> src/index.js

echo "**/node_modules" > .gitignore

echo "# $projectName" > README.md

cat > package.json <<EOF
{
	"name": "$projectName",
	"version": "1.0.0",
	"description": "",
	"main": "src/index.js",
	"author": "fatlard1993",
	"license": "ISC",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/fatlard1993/$projectName.git"
	},
	"bugs": {
		"url": "https://github.com/fatlard1993/$projectName/issues"
	},
	"homepage": "https://github.com/fatlard1993/$projectName#readme",
	"eslintConfig": {
		"extends": "rules"
	},
	"devDependencies": {
		"babel-eslint": "^10.0.1",
		"eslint": "^5.15.1",
		"eslint-config-rules": "github:fatlard1993/eslint-config-rules"
	}
}
EOF

npm i