#!/bin/bash

activeWindowClass=`i3-window-active-class`
terminalApp="Gnome-terminal"

sleep 0.1

if [ "$activeWindowClass" == "$terminalApp" ]; then
	xdotool key --clearmodifiers "ctrl+shift+$1"
else
	xdotool key --clearmodifiers "ctrl+$1"
fi
