#!/bin/sh

case "$1" in
  lock)
    #killall -SIGUSR1 dunst # pause
    #killall -SIGUSR2 dunst # resume

    screenCap=~/.i3/screen_locked.png
    scrot $screenCap && convert $screenCap -blur 8x8 $screenCap
    i3lock -i  $screenCap 
  ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    pm-suspend
    ;;
  hibernate)
    pm-hibernate
    ;;
  reboot)
    shutdown -r now
    ;;
  update_and_reboot)
    apt update -y && apt upgrade -y && shutdown -r now
    ;;
  shutdown)
    shutdown -h now
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac
