#!/bin/sh

case "$1" in
  lock)
    #killall -SIGUSR1 dunst # pause
    #killall -SIGUSR2 dunst # resume

    screenCap=$HOME/.config/i3/.screen_locked.png
    scrot $screenCap && convert $screenCap -blur 8x8 $screenCap
    i3lock -i $screenCap
  ;;
  exit)
		i3-msg [class=".*"] kill

    i3-msg exit
    ;;
  reboot)
		i3-msg [class=".*"] kill

    shutdown -r now
    ;;
  shutdown)
		i3-msg [class=".*"] kill

    shutdown -h now
    ;;
  *)
    echo "Usage: $0 {lock|exit|reboot|shutdown}"
    exit 2
esac
