#!/bin/bash

if [[ `whoami` != "root" ]]; then
	echo -e "This script needs to be run as root ... Restarting with sudo\n"

	exec sudo $(dirname $(readlink -f $0))/$(basename $0) $@

	exit #?
fi

echo `lsblk | grep -v snap`

echo -e "\nYou have selected: $2\nPress enter to continue...\n"

read -p ""

sudo umount $2

sudo dd bs=4M if=$1 of=$2 conv=fdatasync status=progress

sync