#!/bin/bash

source enforceSudo

echo `lsblk | grep -v snap`

echo -e "\nYou have selected: $2\nPress enter to continue...\n"

read -p ""

umount $2

dd bs=4M if=$1 of=$2 conv=fdatasync status=progress

sync