#!/bin/bash

if [ -s "$HOME/.bashrc.bkup" ]; then
	echo "Restoring default bashrc"

	mv $HOME/.bashrc.bkup $HOME/.bashrc
	sudo mv /root/.bashrc.bkup /root/.bashrc
fi

if [ ! -s "$HOME/.bashrc.bkup" ]; then
	echo -e "Backing up and extending .bashrc\n"

	cp $HOME/.bashrc $HOME/.bashrc.bkup
	sudo cp /root/.bashrc /root/.bashrc.bkup

	cat $DOTFILES/etc/.bashrc >> $HOME/.bashrc
	cat $DOTFILES/etc/.bashrc | sudo tee -a /root/.bashrc
fi

echo -e "\nUpdating bashrc.d"

mkdir -p $HOME/.bashrc.d
sudo mkdir -p /root/.bashrc.d

files=$(find $DOTFILES/bashrc/* -type f)

for file in $files; do
	ln -sf $file $HOME/.bashrc.d/$(basename $file)
	sudo ln -sf $file /root/.bashrc.d/$(basename $file)
done