#!/bin/bash

echo "Installing apt packages for i3"

apt-autoinstall i3 libnotify-bin fonts-font-awesome feh imagemagick xdotool wmctrl xautolock caffeine

echo "Generating i3 config"

if [ ! "$DOTFILES" ]; then
	echo "error"
	notify-send "$(pwd)"

	exit 1
fi

i3_folder=$DOTFILES/i3
device_i3_folder=$DOTFILES/devices/$DOTFILES_DEVICE/i3

mkdir -p $HOME/.config/i3

echo "set \$dotfilesFolder $DOTFILES" > /tmp/i3SysVars
echo "set \$dotfilesDevice $DOTFILES_DEVICE" >> /tmp/i3SysVars
echo "set \$deviceFolder $DOTFILES/devices/$DOTFILES_DEVICE" >> /tmp/i3SysVars

cat $DOTFILES/etc/_fileWarning \
  <(echo) $i3_folder/_theme \
	<(echo) /tmp/i3SysVars \
  <(echo) $i3_folder/_variables \
  <(echo) $device_i3_folder/_variables \
  <(echo) $i3_folder/_config \
  <(echo) $device_i3_folder/_config \
  <(echo) $i3_folder/_shortcuts \
  <(echo) $device_i3_folder/_shortcuts \
  <(echo) $i3_folder/_modes \
  <(echo) $device_i3_folder/_modes \
  <(echo) $i3_folder/_startup \
  <(echo) $device_i3_folder/_startup \
  <(echo) $i3_folder/_i3bar \
> $HOME/.config/i3/config

cat $DOTFILES/etc/_fileWarning \
  <(echo) $i3_folder/_status_theme \
  <(echo) $i3_folder/_status_items \
  <(echo) $device_i3_folder/_status_order \
> $HOME/.config/i3/status.conf

if [ -s "$device_i3_folder/_status2_order" ]; then
  cat $DOTFILES/etc/_fileWarning \
    <(echo) $i3_folder/_status_theme \
    <(echo) $i3_folder/_status_items \
    <(echo) $device_i3_folder/_status2_order \
  > $HOME/.config/i3/status2.conf

  cat <(echo) $i3_folder/_i3bar2 >> $HOME/.config/i3/config
fi

i3-msg restart