#!/bin/bash

DOTFILES=$(cd $(dirname $(readlink -f $0))/.. && pwd)
DOTFILES_DEVICE=$(cat $DOTFILES/temp/deviceType)

echo "Setting up fonts"

mkdir -p $HOME/.fonts

files=$(find $DOTFILES/fonts/* -type f)

for file in $files; do
	ln -sf $file $HOME/.fonts/$(basename $file)
done

sudo fc-cache -v