#!/bin/bash

shopt -s nullglob

WALLPAPER_DIR=~/Pictures/Wallpapers
STASH_DIR=$WALLPAPER_DIR/../notWallpapers
TMP_DIR=/tmp/wallpapers

touch $WALLPAPER_DIR/.ignore

mkdir -p $TMP_DIR $WALLPAPER_DIR/saved $STASH_DIR

COMMAND=$1
OPTION=$2

if [ "$COMMAND" = "get" ]; then
	if [ -f $TMP_DIR/subreddits ]; then
		read -a SUBREDDITS < $TMP_DIR/subreddits
	else
		if [ -f $WALLPAPER_DIR/.subreddits ]; then
			read -a SUBREDDITS < $WALLPAPER_DIR/.subreddits
		else
			SUBREDDITS=("wallpapers" "earthview" "EarthPorn" "DesktopLego" "BackgroundArt" "HI_Res" "SpecArt" "MinimalWallpaper" "BattlePaintings" "Medievalart" "ShittyMsPaint")
		fi

		echo "${SUBREDDITS[*]}" > $TMP_DIR/subreddits
	fi

	if [ ! $SUBREDDITS ]; then
		notify-send "Wallpaper" "No subreddits to scan!"

		exit 1
	fi

	REDDIT="http://www.reddit.com/r/"
	IMAGE_COUNT_TO_DOWNLOAD=${2:-3}
	SUBREDDIT=${3:-${SUBREDDITS[$RANDOM % ${#SUBREDDITS[@]}]}}

	LINKS=$(wget -q $REDDIT${SUBREDDIT}.rss -O - | grep -Po 'http((?!&quot;|"|icon|thumb).)*j?pn?g' | shuf)
	DOWNLOADED_COUNT=0

	for LINK in $LINKS
	do
		echo -e "Downloading: $LINK\n"

		FILENAME=$(echo $LINK | grep -Po '(?=\w+\.\w{3,4}$).+')
		TMP_FILE=$TMP_DIR/$FILENAME

		wget -qc $LINK -O $TMP_FILE

		FILE_SUM=$(md5sum "$TMP_FILE" | cut -d' ' -f1)

		if stat -t $WALLPAPER_DIR/**/$FILE_SUM.* >/dev/null 2>&1 ; then
			echo -e "Already have: $FILE_SUM\n"

			rm $TMP_FILE
		elif stat -t $WALLPAPER_DIR/../**/$FILE_SUM.* >/dev/null 2>&1 ; then
			echo -e "Already have: $FILE_SUM\n"

			rm $TMP_FILE
		elif grep -q "$FILE_SUM" "$WALLPAPER_DIR/.ignore" ; then
			echo -e "Didnt like: $FILE_SUM\n"

			rm $TMP_FILE
		else
			mv $TMP_FILE $WALLPAPER_DIR/$FILE_SUM.${FILENAME##*.}

			echo -e "Saved: $FILE_SUM\n"

			(( DOWNLOADED_COUNT = DOWNLOADED_COUNT + 1 ))
		fi

		if [ $DOWNLOADED_COUNT = $IMAGE_COUNT_TO_DOWNLOAD ]; then
			break
		fi
	done

	if [ $DOWNLOADED_COUNT = 0 ]; then
		notify-send "Wallpaper" "No new images from $SUBREDDIT today"

		sed -ie "s/$SUBREDDIT[ ]*//g" $TMP_DIR/subreddits

		exit 0
	fi

	notify-send "Wallpaper" "Downloaded_COUNT $DOWNLOADED_COUNT wallpapers from $SUBREDDIT"

	if (( DOWNLOADED_COUNT < IMAGE_COUNT_TO_DOWNLOAD )); then
		(( IMAGE_COUNT_TO_DOWNLOAD = IMAGE_COUNT_TO_DOWNLOAD - DOWNLOADED_COUNT ))

		sed -ie "s/$SUBREDDIT[ ]*//g" $TMP_DIR/subreddits

		$0 get $IMAGE_COUNT_TO_DOWNLOAD
	fi
elif [ "$COMMAND" = "change" ]; then
	if [ "$OPTION" = "saved" ]; then
		WALLPAPER=$(ls $WALLPAPER_DIR/saved/*.* | shuf -n 1)
	elif [ "$OPTION" = "unsorted" ]; then
		WALLPAPER=$(ls $WALLPAPER_DIR/*.* | shuf -n 1)
	fi

	if echo "$WALLPAPER" | grep -P "\.j?pn?g$" ; then
		feh --bg-fill $WALLPAPER

		echo $WALLPAPER > $WALLPAPER_DIR/.current
	else
		echo "$WALLPAPER is not supported .. Must be one of: jpg, png"

		$0 change saved
	fi
elif [ "$COMMAND" = "sort" ]; then
	CURRENT_WALLPAPER=$(cat $WALLPAPER_DIR/.current)

	if [ ! -e $CURRENT_WALLPAPER ]; then
		notify-send "Wallpaper" "No wallpaper to $OPTION!"

		exit 0
	fi

	FILE_SUM=$(md5sum "$CURRENT_WALLPAPER" | cut -d' ' -f1)

	if [ "$OPTION" = "delete" ] || [ "$OPTION" = "stash" ]; then
		echo -e "$FILE_SUM\n" >> $WALLPAPER_DIR/.ignore
	fi

	if [ "$OPTION" = "delete" ]; then
		rm $CURRENT_WALLPAPER
	else
		SUBFOLDER=${3:-"${OPTION}ed"}

		mkdir -p $WALLPAPER_DIR/$SUBFOLDER

		mv $CURRENT_WALLPAPER $WALLPAPER_DIR/$SUBFOLDER/$FILE_SUM.${CURRENT_WALLPAPER##*.}
	fi

	$0 change unsorted
elif [ "$COMMAND" = "convert" ]; then
	SUBFOLDER=${2:-"saved"}
	FILES=$(ls $WALLPAPER_DIR/$SUBFOLDER/*.*)

	for FILE in $FILES
	do
		FILE_SUM=$(md5sum "$FILE" | cut -d' ' -f1)

		echo -e "OLD: $FILE\nNEW: $WALLPAPER_DIR/$SUBFOLDER/$FILE_SUM.${FILE##*.}"
		mv $FILE $WALLPAPER_DIR/$SUBFOLDER/$FILE_SUM.${FILE##*.}
	done
else
	echo -e "Useage: PATH/wallpaper [command] [option(s)]\n\
	get     |IMAGE_COUNT_TO_DOWNLOAD ?SUBREDDIT?|\n\
	change  |saved|unsorted|\n\
	sort    |delete|save|stash|\n\
	convert |SUBFOLDER|"
fi