#!/bin/bash

for command in youtube-dl ffmpeg; do
	if [ ! $(which $command) ]; then
		zenity --error --text "Could not find \"$command\" application.\n
Make sure ffmpeg is installed and \"$command\" is executable."
		exit 1
	fi
done

url=`zenity --entry --title="Download From Youtube" --text="Enter address youtube video:                              "`

if [ $? = 0 ]; then
	filetype=`zenity  --list  --text "mp3 or mp4" --radiolist  --column "select" --column "type" TRUE "mp3" FALSE "mp4"`

	if [ $? = 0 ] ; then
		if [ $filetype = "mp3" ]; then
			youtube-dl "$url" --extract-audio --audio-format=mp3 | zenity --progress --pulsate --auto-close --auto-kill --title="Download From Youtube" --text="downloading..."
		else
			youtube-dl "$url" | zenity --progress --pulsate --auto-close --auto-kill --title="Download From Youtube" --text="downloading..."
		fi
	fi
fi