#!/bin/bash

function promptCommand {
	c0="\[\e[0m\]"
	cdef="\[\e[39m\]"
	ccyan="\[\e[36m\]"
	clcyan="\[\e[96m\]"
	cpurp="\[\e[35m\]"
	clpurp="\[\e[95m\]"
	cblu="\[\e[34m\]"
	clblu="\[\e[94m\]"
	cyel="\[\e[33m\]"
	clyel="\[\e[93m\]"
	cgrn="\[\e[32m\]"
	clgrn="\[\e[92m\]"
	cred="\[\e[31m\]"
	clred="\[\e[91m\]"
	cblk="\[\e[30m\]"
	clgrey="\[\e[37m\]"
	cgrey="\[\e[90m\]"

	promptReset="\e(B\e[m"
	lastCommand=$(history | tail -n1 | sed 's/^[[:space:]][0-9]*[[:space:]]*//g')
	expandingPipe="\e7\e[1A┣\e8┗"
	prePrompt=" \$ "
	hostname="\H"
	gitBranch=`[ -d .git ] && echo "${clcyan}[${ccyan}$(git name-rev --name-only @)${clcyan}]"`
	user="${clgrn}[${cgrn}\u${clgrn}@${cgrn}${hostname}${clgrn}]"
	adminUser="${clyel}[${cyel}\u${clyel}@${cyel}${hostname}${clyel}]"
	directory="${clblu}[${cblu}\w${clblu}]"
	tty="${clpurp}[${cpurp}\l${clpurp}]"
	time="${cdef}[${clgrey}$(date '+%T')${cdef}]"

	trap 'tput sgr0' DEBUG

	if [[ `whoami` == "root" ]]; then
		PS1="${c0}${cred}┏${time}${tty}${adminUser}${directory}${gitBranch}\n${cred}┗${prePrompt}"

		PS2="${c0}${cred}${expandingPipe}${prePrompt}"
	else
		PS1="${c0}${cdef}┏${time}${tty}${user}${directory}${gitBranch}\n${cdef}┗${prePrompt}"

		PS2="${c0}${cdef}${expandingPipe}${prePrompt}"
	fi
}

PROMPT_COMMAND=promptCommand