Section "InputClass"
	Identifier "Touchpad settings"
	MatchIsTouchpad "on"
	Option "Tapping" "off"
	Option "TappingDrag" "off"
	Option "NaturalScrolling" "on"
	Option "ClickMethod" "clickfinger"
	Option "AccelSpeed" "0.5"
EndSection
