#!/bin/bash

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_theme \
  <(echo) ~/dotfiles/devices/xps_13_9360/i3/_variables \
  <(echo) ~/dotfiles/devices/xps_13_9360/i3/config \
  <(echo) ~/dotfiles/i3/config \
  <(echo) ~/dotfiles/i3/i3bar \
  <(echo) ~/dotfiles/i3/modes \
  <(echo) ~/dotfiles/devices/xps_13_9360/i3/startup \
> ~/.i3/config

cat ~/dotfiles/_fileWarning \
  <(echo) ~/dotfiles/i3/_status_theme \
  <(echo) ~/dotfiles/i3/_status_items \
  <(echo) ~/dotfiles/devices/xps_13_9360/i3/_status_order \
> ~/.i3/status.conf

cp ~/dotfiles/scripts/getWindowCriteria ~/.i3/
cp ~/dotfiles/scripts/ledCtl ~/.scripts/
cp ~/dotfiles/scripts/system ~/.scripts/
cp ~/dotfiles/scripts/clipd  ~/.scripts/
cp ~/dotfiles/scripts/wallpaper  ~/.scripts/

i3-msg restart