#!/bin/zsh

thisPath=`dirname ${BASH_SOURCE[0]:-${(%):-%x}}`

source "$thisPath/lang"
source "$thisPath/path"

export EDITOR='/usr/local/bin/code'
export VISUAL='/usr/local/bin/code'
export PAGER='less'