#!/bin/zsh

# Base Path
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

# Dotfiles Bin
PATH="$PATH:$HOME/.dotfiles/bin"

# Local Bin
PATH="$PATH:$PWD/bin"

# NPM Bin
PATH="$PATH:$HOME/.npm-global/bin"