#!/bin/zsh

# Ripgrep config
export RIPGREP_CONFIG_PATH="$HOME/.dotfiles/.ripgreprc"

# Base Path
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

# NPM Bin
export PATH="$PATH:$HOME/.npm-global/bin"

# Local User Bin
export PATH="$PATH:$HOME/bin"

# Local User Bin
export PATH="$PATH:$HOME/.local/bin"

# Dotfiles Bin
export PATH="$PATH:$HOME/.dotfiles/bin"

# Bun
export PATH="$PATH:$HOME/.bun/bin"

