#!/bin/bash

if [ ! -e $HOME/.config/device ]; then
  echo "No valid device file!"
  exit 1
fi

device=$(cat $HOME/.config/device)
dotfiles_folder=$HOME/Projects/dotfiles
device_folder=$dotfiles_folder/devices/$device

sudo mkdir -p /etc/X11/xorg.conf.d

sudo cp $device_folder/xorg/*.conf /etc/X11/xorg.conf.d/